### ISSUE TITLE
Support for API-keys

### ISSUE THREAD

**Issue by houtari** [GispoCoding/QGISDigitransitGeocoding#20]
Starting from 3.4.2023, the use of Digitransit APIs will require registration and use of API keys, so this support should be added to this plugin tool by that date or else the plugin will not work from that date onwards. See [https://digitransit.fi/en/developers/api-registration/](https://digitransit.fi/en/developers/api-registration/) for more details.

**Comment by ernoma** [comment]
@houtari and GispoCoding, The possibility to register and get the API keys has started. More info https://digitransit.fi/en/developers/api-registration/ and sign up for to get the API keys: https://portal-api.digitransit.fi/. Anyone with an email address who accepts the privacy policy statement by HRT (HSL) can register.

**Comment by JuhoErvasti** [comment]
@houtari @ernoma  We've prepared an update which makes it possible to use the plugin with an API key. The update will go live to this repo and the QGIS repo hopefully next week.

**Comment by houtari** [comment]
OK! Thanks @JuhoErvasti for letting us at HSL know the situation.

**Comment by ernoma** [comment]
@JuhoErvasti Very great news! Thank you for the info!

**Comment by JuhoErvasti** [comment]
@houtari @ernoma I've pushed the new version to this repo and it can be installed from [this zip file](https://github.com/GispoCoding/QGISDigitransitGeocoding/releases/download/0.7.2/QGISDigitransitGeocoding-master-0.7.2.zip), in case you need to use it immediately. I also added instructions on how to use the plugin with the API key to the readme.

We'll push the update to the OSGeo plugin repo later, again hopefully this week and I'll close this issue then. Please let us know if there are any issues with the update.

**Comment by ernoma** [comment]
@JuhoErvasti Thank you for the info and for the working update!

I used the plugin successfully with the DIGITRANSIT_API_KEY variable.

**Comment by JuhoErvasti** [comment]
Update is now live in the official QGIS repository, I'll close this issue.
